### ISSUE TITLE
cinnamon_js_add_extension_importer error (it no longer exists)

### ISSUE THREAD

**Issue by leigh123linux** [lestcape/Drives-Manager#12]
```
Cjs-Message: JS LOG: error: Failed of Drives Manager:: Could not locate cinnamon_js_add_extension_importer: 'cinnamon_js_add_extension_importer': /usr/lib64/cinnamon/libcinnamon-js.so: undefined symbol: cinnamon_js_add_extension_importer
```

https://github.com/linuxmint/Cinnamon/pull/4537

**Comment by lestcape** [comment]
@leigh123linux thanks. In that thread, I mention that this will be big deal to all my current code. In all cases Drive Manager is working in my PC. I have 3 historical ways to auto-import my extension as an applet/desklet...

cinnamon --version
Cinnamon 3.0.4

If you speak about the version in spice web site, yes, i don't know what i have there. Have things in spices is just only a pain, if i have not time to working on it.

Regards.

**Comment by steveadoo2** [comment]
I also have this problem running Linux Mint 17.3 Cinnamon 2.8.8 - 64 bit. Meaning I can't show the manager as an applet :(

**Comment by lestcape** [comment]
@steveadoo2 download the github version:
https://github.com/lestcape/Drives-Manager/archive/master.zip

**Comment by lestcape** [comment]
This desklet, will not logger available for cinnamon desktop any more, at less not because of me. I'm on gnome shell now.
